server {
    listen 80;
    listen [::]:80;
    server_name site.void-rp.ru;

    root /var/www/voidrp-site/dist;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /assets/ {
        expires 30d;
        add_header Cache-Control "public, immutable";
    }
}
